name: Python CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        # The -e .[dev] assumes your pyproject.toml is set up for editable installs with a [dev] extra.
        # If not using extras, or if you prefer pip install -r requirements-dev.txt, adjust accordingly.

    - name: Run linters and tests
      run: |
        scripts/lint-and-test.sh
        # Alternatively, run commands directly:
        # ruff check .
        # black --check .
        # mypy .
        # pytest

    # Optional: Add step to build and push Docker images to GHCR on merge to main
    # - name: Log in to GitHub Container Registry
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    # - name: Build and push BuyerConcierge Docker image
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     file: ./buyer_concierge/Dockerfile
    #     push: true
    #     tags: ghcr.io/${{ github.repository_owner }}/buyer_concierge:latest,ghcr.io/${{ github.repository_owner }}/buyer_concierge:${{ github.sha }}

    # - name: Build and push SupplierQuoter Docker image
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     file: ./supplier_quoter/Dockerfile
    #     push: true
    #     tags: ghcr.io/${{ github.repository_owner }}/supplier_quoter:latest,ghcr.io/${{ github.repository_owner }}/supplier_quoter:${{ github.sha }} 